# Site settings
title: "Ennsights"

description: "Find your deeper self."

email: 'info@bowtie.co'

baseurl:  # the subpath of your site, e.g. /blog/

url: "https://ennsights.com" # the base hostname & protocol for the site

logourl:  # Site logo

author: "Stephanie Grant"
author_thumbnail: "" # Author avatar

# Theme additions - please update the default values

mailchimp_username: bowtie
mailchimp_server: us5
mailchimp_apikey: 85cc3923dcbe51832fa566843
mailchimp_listid: d4c3230a3a

google_analytics_id:   # Your google analytics ID (e.g. 'UA-XXXXXXXX-X')
google_tag_manager: # Your google analytics ID (e.g. 'UA-XXXXXXXX-X')

google_api_key:  # Your Google API key for Maps


bowtietheme:

  # Contact info, leave blank to ignore
  contact:
    company: Ennsights
    address: 20956 Vista Bonita Dr
    city: Bend
    state: OR
    zip: 97217
    country: USA
    phone: (541) 317 5012
    latlng:  # (e.g. '39.733536,-104.992611')
    twitter:  # (e.g. 'bowtie_co')
    facebook:  # (e.g. 'bowtieagency')
    github:  # (e.g. 'bowtie-io')
    instagram:  # (e.g. 'bowtieagency')
    flickr: #groups/2772799@N24/ # (e.g. 'groups/2772799@N24/')
    linkedin:  # (e.g. 'company/bowtie')
    youtube: #channel/UCovWO5keLOLcLu8WdO-ABJw # (e.g. 'channel/UCovWO5keLOLcLu8WdO-ABJw')

  # Author attribution data
  authors:
    chad:
      display_name: STEPHANIE GRANT
      avatar:
      gravatar: 82f60d4376bab6a31f85211a9345303f
      email: chad@bowtie.co
      web: https://bowtie.co/
      twitter: chadperson
      medium: no-buffer
      github: chadperson
      bio: Founder and CEO

collections:
  posts:
    output: true
    permalink: /:path/
  portfolios:
    output: true
    permalink: /portfolio/:path/
  services:
    output: true
    permalink: /:path/
  serviceblocks:
    output: false
    permalink: /:path/
  team:
    output: false
    permalink: /:path/
  lander-1-col:
    output: true
  lander-2-col:
    output: true
  dev-pricing:
    output: false
  testimonials:
    output: false

defaults:
  -
    scope:
      type: "services"
    values:
      layout: "service"
  -
    scope:
      type: "portfolios"
    values:
      layout: "portfolio"
  - scope:
      collection: lander-1-col
    values:
      layout: "lander-simple-singlecol"

# Permalinks
permalink: /:categories/:title/
relative_permalinks: false

plugins_dir: #
plugins:
  [jekyll-redirect-from]

# Pagination config
#paginate: 5
#paginate_path: "/blog/page:num/"

#compress sass
sass:
  style: compressed

keep_files: # Files/Folders located inside the ./_site folder to be retained on build (e.g.'[.git, .svn]')
  - docs
  - assets

# Files/Folders to be excluded from generated _site folder
exclude:
  - .gitignore
  - .sass-cache

#toggle future post dates back on
future: true
